from pathlib import Path
p=Path('/home/ubuntu/work/yawaqit_extract/index.html')
s=p.read_text()
start=s.index('const TXT={')
end=s.index('function T(', start)
block=r'''const TXT={
 ar:{settingsTheme:'مظهر التطبيق',language:'لغة القرآن والواجهة',chooseLanguage:'اختر اللغة',morningMode:'وضع صباحي',nightMode:'وضع ليلي',prayerNotifications:'إشعارات الصلاة',enabled:'مفعلة',disabled:'متوقفة',adhanSound:'صوت الأذان',fajrAdhanSound:'صوت أذان الفجر',dailyReminders:'تذكيرات المناسبات',reminderHour:'ساعة التذكير',close:'إغلاق',previousPrayer:'الصلاة السابقة',nextPrayer:'الصلاة القادمة',fullVideo:'فيديو كامل',openYouTube:'فتح الفيديو في YouTube إذا لم يعمل التشغيل داخل الصفحة ↗',videoList:'فيديو وخطبة ورسالة يومية',share:'إعادة نشر',like:'إعجاب',playFromSource:'تشغيل الفيديو',quranTitle:'المصحف الشريف',surahs:'سورة',searchSurah:'ابحث عن اسم السورة أو رقمها',searchContent:'ابحث داخل المحتوى',translate:'الترجمة',translation:'العربية',noResults:'لا توجد نتائج مطابقة',next:'التالي',result:'النتيجة',quiz:'تحدي الأسئلة',answered:'المجاب',correct:'الصحيح',final:'النتيجة النهائية',retry:'إعادة التحدي',audioDetails:'تفاصيل الصوت',reader:'القارئ',surah:'السورة',ayah:'الآية',playSurah:'تشغيل السورة كاملة',stop:'إيقاف',tafsir:'التفسير الميسر',dailyVerse:'آية وعبرة',about:'بعد كل ضيق فرج قريب',adhkar:'كل الأذكار',search:'ابحث هنا',selectReader:'اختر القارئ',selectSurah:'اختر السورة',listen:'اضغط تشغيل للاستماع',playing:'يتم التشغيل الآن'},
 en:{settingsTheme:'App appearance',language:'Quran and interface language',chooseLanguage:'Choose language',morningMode:'Light mode',nightMode:'Dark mode',prayerNotifications:'Prayer notifications',enabled:'Enabled',disabled:'Disabled',adhanSound:'Adhan sound',fajrAdhanSound:'Fajr adhan sound',dailyReminders:'Daily reminders',reminderHour:'Reminder hour',close:'Close',previousPrayer:'Previous prayer',nextPrayer:'Next prayer',fullVideo:'Full video',openYouTube:'Open on YouTube if playback does not work here ↗',videoList:'Videos, sermons and daily messages',share:'Repost',like:'Like',playFromSource:'Play video',quranTitle:'The Noble Quran',surahs:'surahs',searchSurah:'Search by surah name or number',searchContent:'Search inside content',translate:'Translation',translation:'English',noResults:'No matching results',next:'Next',result:'Result',quiz:'Quiz challenge',answered:'Answered',correct:'Correct',final:'Final score',retry:'Try again',audioDetails:'Audio details',reader:'Reciter',surah:'Surah',ayah:'Ayah',playSurah:'Play whole surah',stop:'Stop',tafsir:'Tafsir',dailyVerse:'Verse & reflection',about:'After every hardship comes ease',adhkar:'All adhkar',search:'Search here',selectReader:'Choose reciter',selectSurah:'Choose surah',listen:'Press play to listen',playing:'Playing now'},
 fr:{settingsTheme:'Apparence',language:'Langue du Coran et de l’interface',chooseLanguage:'Choisir la langue',morningMode:'Mode clair',nightMode:'Mode sombre',prayerNotifications:'Notifications de prière',enabled:'Activées',disabled:'Désactivées',adhanSound:'Son de l’adhan',fajrAdhanSound:'Son de l’adhan du Fajr',dailyReminders:'Rappels quotidiens',reminderHour:'Heure du rappel',close:'Fermer',previousPrayer:'Prière précédente',nextPrayer:'Prochaine prière',fullVideo:'Vidéo complète',openYouTube:'Ouvrir sur YouTube si la lecture échoue ici ↗',videoList:'Vidéos, sermons et messages quotidiens',share:'Reposter',like:'J’aime',playFromSource:'Lire la vidéo',quranTitle:'Le Noble Coran',surahs:'sourates',searchSurah:'Rechercher par nom ou numéro',searchContent:'Rechercher dans le contenu',translate:'Traduction',translation:'Français',noResults:'Aucun résultat',next:'Suivant',result:'Résultat',quiz:'Défi de questions',answered:'Répondues',correct:'Correctes',final:'Résultat final',retry:'Recommencer',audioDetails:'Détails audio',reader:'Récitateur',surah:'Sourate',ayah:'Verset',playSurah:'Lire la sourate entière',stop:'Arrêter',tafsir:'Tafsir',dailyVerse:'Verset et réflexion',about:'Après toute difficulté vient la facilité',adhkar:'Tous les adhkar',search:'Rechercher',selectReader:'Choisir le récitateur',selectSurah:'Choisir la sourate',listen:'Appuyez sur lecture',playing:'Lecture en cours'},
 ur:{settingsTheme:'ایپ کا انداز',language:'قرآن اور انٹرفیس کی زبان',chooseLanguage:'زبان منتخب کریں',morningMode:'دن کا موڈ',nightMode:'رات کا موڈ',prayerNotifications:'نماز کی اطلاعات',enabled:'فعال',disabled:'غیر فعال',adhanSound:'اذان کی آواز',fajrAdhanSound:'فجر کی اذان کی آواز',dailyReminders:'روزانہ یاد دہانیاں',reminderHour:'یاد دہانی کا وقت',close:'بند کریں',previousPrayer:'پچھلی نماز',nextPrayer:'اگلی نماز',fullVideo:'مکمل ویڈیو',openYouTube:'اگر یہاں نہ چلے تو YouTube پر کھولیں ↗',videoList:'ویڈیوز، خطبات اور روزانہ پیغامات',share:'دوبارہ نشر',like:'پسند',playFromSource:'ویڈیو چلائیں',quranTitle:'قرآن مجید',surahs:'سورتیں',searchSurah:'سورت کے نام یا نمبر سے تلاش کریں',searchContent:'مواد میں تلاش کریں',translate:'ترجمہ',translation:'اردو',noResults:'کوئی نتیجہ نہیں',next:'اگلا',result:'نتیجہ',quiz:'سوالات کا چیلنج',answered:'جواب دیے',correct:'درست',final:'حتمی نتیجہ',retry:'دوبارہ شروع',audioDetails:'آڈیو کی تفصیل',reader:'قاری',surah:'سورت',ayah:'آیت',playSurah:'مکمل سورت چلائیں',stop:'روکیں',tafsir:'تفسیر',dailyVerse:'آیت اور سبق',about:'ہر مشکل کے بعد آسانی ہے',adhkar:'تمام اذکار',search:'تلاش کریں',selectReader:'قاری منتخب کریں',selectSurah:'سورت منتخب کریں',listen:'سننے کے لیے چلائیں',playing:'اب چل رہا ہے'}
};
'''
s=s[:start]+block+s[end:]
p.write_text(s)
print('translation block fixed')
